### ISSUE TITLE
dps.network label not working

### ISSUE THREAD

**Issue by bootsie123** [mageddo/dns-proxy-server#207]
### What is Happening

Hi! I'm trying to use DPS in a Docker swarm to manage private containers when using a VPN. I have a few containers which use multiple networks. In my case, I have a network specifically for containers that can be accessed via the VPN. What happens is DPS resolves the IP to be another network. Even though I specified via labels to use the `VPN network.

### What is expected

If I understand the documentation correctly, when adding the `dps.network` label, I can specify which network to use when resolving the IP. In my situation I expect the VPN network to be used instead of other networks.

### Steps to Reproduce

Here's my docker-compose file for DPS:

```
version: '3.3'
services:
  dnsproxy:
    image: defreitas/dns-proxy-server:latest
    hostname: dns.local
    environment:
      MG_REGISTER_CONTAINER_NAMES: '1'
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /etc/resolv.conf:/etc/resolv.conf
    networks:
     - vpn
    logging:
      driver: json-file
networks:
  vpn:
    external: true
```

and here's the docker-compose file for the test service I'm using:

```
version: '3.3'
services:
  goofy_elgamal:
    image: nginxdemos/hello:latest
    hostname: test.local
    networks:
     - proxy
     - vpn
    logging:
      driver: json-file
    deploy:
      mode: global
      labels:
        dps.network: vpn
networks:
  proxy:
    external: true
  vpn:
    external: true
```

**Specs:**
- OS: `Ubuntu 18.04`
- Docker Version: `19.03.12, build 48a66213fe`
- DPS Version: `2.19.0`
