### ISSUE TITLE
Running dns-proxy-server makes docker image builds fail, with `cannot resolve host` errors

### ISSUE THREAD

**Issue by SimJoSt** [mageddo/dns-proxy-server#251]
### What is Happening

* Building docker images with the need to resolve external dependencies throws "cannot resolve host" errors.

### What is expected

Docker image builds are not affected.
Either they resolve normally or through dns-proxy-server

### Steps to Reproduce

1. Have a dns-proxy-server running
2. Start a Docker image build with the need to resolve external dependencies

**Specs:**
- OS: Debian 10 Buster
- Docker Version: 20.10.21
- DPS Version: 2.19.0

**Comment by zxzharmlesszxz** [comment]
UP!

**Comment by mageddo** [comment]
Hey, I wasn't able to reproduce this behavior, What I noticed is that docker caches the DNS server address, so if you start DPS, restart docker, then restart DPS again and it get a new docker container IP then you can get an issue, because docker cached the previous DPS IP and will try to solve names from an IP that is not DPS server anymore. I think there's no much DPS can do in this case.

Can you please confirm if your usecase is something like that or give more details on the steps to reproduce it?

If your usecase is the mentioned, then you can lead with this by fixing a IP address to the DPS container by using `docker run --ip ... ` .

Thanks in advance.

**Comment by mageddo** [comment]
@zxzharmlesszxz @SimJoSt

**Comment by mageddo** [comment]
I've noticed that this  can be related to this one  https://github.com/mageddo/dns-proxy-server/issues/248, if DPS use systemd-resolved instead of the resolv.conf file this issue may  disappear

**Comment by SimJoSt** [comment]
We don't restart the containers that much on their own, so I don't think thus would be it. Of course it could be possible.
I'll check that out on the next maintenance.
It will take a few days at least to confirm this is fixes the issue.

**Comment by zxzharmlesszxz** [comment]
It is possible if you run dns-proxy container at the different network than other containers, example:
- run dns-proxy at dns network
- run test container at the test network
What's happened?
DNS not resolved!
Example 2:
When your dns-proxy container is running at different than default network,
run build container command, what happens:
- DNS-proxy at the different network
- build process running at the default network
Build process doesn't have access to dns-proxy to resolve names

**Comment by mageddo** [comment]
Hey @zxzharmlesszxz , it would be easier to understand the scenario with a minimal reproducible example, focusing on your first example, I tried the below but still works

```yml
version: '3'
services:
  dps:
    image: defreitas/dns-proxy-server:2.19.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    hostname: dns.mageddo
    networks:
      dns:
  nginx:
    image: nginx:1.22
    hostname: nginx.app
    networks:
      test:

networks:
  dns:
  test:

```

```bash
curl -I nginx.app
HTTP/1.1 200 OK
Server: nginx/1.22.1
```
