### ISSUE TITLE
Include wget command in image for healthcheck

### ISSUE THREAD

**Issue by gjrtimmer** [mageddo/dns-proxy-server#331]
### What is expected

wget command to be available so healthcheck can be used

### What is Happening

wget command not included in image

### Changes (Optional)

Please add wget command to image.

docker-compose.yml healthcheck
```yaml
healthcheck:
    test: wget --no-verbose --tries=1 --no-check-certificate --spider http://localhost:5380
    interval: 10s
    timeout: 10s
    retries: 3
    start_period: 10s
```
