### ISSUE TITLE
Running in a container with DPS_NETWORK feature not working as expected

### ISSUE THREAD

**Issue by Sajito** [mageddo/dns-proxy-server#347]
Really cool to see this project being actively developed again.

### What is Happening

I'm running the dns server in a docker container and want to use the DPS_NETWORK feature. This is my `docker-compose.yml`.

```yaml
version: '3.6'

services:
  dns:
    image: defreitas/dns-proxy-server:3.8.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc:/host/etc
    environment:
      MG_RESOLVCONF: /host/etc/resolv.conf
      MG_DPS_NETWORK: true
      MG_DPS_NETWORK_AUTO_CONNECT: true
```

When the container is started, the dns server is started listening on the container ip address and the container localhost ip address. Then the server connects it's own container to the dps network. Finally it writes the ip address from the dps network to the resolv.conf.
But because the server is not listening on the dps interface, the dns is not reachable. Have a look at this screenshot. If i'd use the initial ip address as dns server, then everything would be fine.

![grafik](https://user-images.githubusercontent.com/6151929/223832541-539f1b21-b1b0-4313-9b1f-8ffbd4139578.png)

### What is expected

Simply said, I'd only expect the automatic configuration to work. I can think of multiple ways to solve this.
- Bind the tcp and udp server to 0.0.0.0 instead of specific interfaces
- Start the tcp and udp server *after* attaching the container to the dps network
- Write the initial network ip address into the resolv.conf

### Specs
- OS: EndeavourOS
- Docker Version: 
  ```
  Client:
  Version:           23.0.1
  API version:       1.42
  Go version:        go1.20
  Git commit:        a5ee5b1dfc
  Built:             Sat Feb 11 13:58:04 2023
  OS/Arch:           linux/amd64
  Context:           default

  Server:
  Engine:
    Version:          23.0.1
    API version:      1.42 (minimum version 1.12)
    Go version:       go1.20
    Git commit:       bc3805a0a0
    Built:            Sat Feb 11 13:58:04 2023
    OS/Arch:          linux/amd64
    Experimental:     false
  containerd:
    Version:          v1.6.19
    GitCommit:        1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f.m
  runc:
    Version:          1.1.4
    GitCommit:        
  docker-init:
    Version:          0.19.0
    GitCommit:        de40ad0
  ```
- DPS Version: Running `/app/dns-proxy-server --version` results in an error (`Unmatched argument at index 0: '/app/dns-proxy-server'`), but I've specified version 3.8.1 in my docker-compose.yml
- The log is pretty short and visible in the screenshot. Hope that's enough.
