### ISSUE TITLE
Option to not comment out existing nameservers from resolv.conf

### ISSUE THREAD

**Issue by Sajito** [mageddo/dns-proxy-server#386]
### What is expected

I'd like to ask for an option, to disable the behavior of disabling existing nameservers. If that option is enabled, it should simply add itself without disabling the other options.

### What is Happening

Currently when dps is started and the file "/etc/resolv.conf" is used, it will comment out any existing nameserver and add itself as single nameserver to the file.

### What I want to achieve

When using my networks dns I can reach other devices in the same network by their hostname. When using dps locally, this ability gets lost.
I could add my networks dns to the "remoteDnsServers" list, but as I'm often in different networks, I'd have to always add the new dns ip addresses to that list.
This should simply work when adding dps as first nameserver in the resolv.conf without disabling all other nameservers.

**Comment by mageddo** [comment]
Sounds good to me, would you prefer to do the configuration by command line, json or env?

**Comment by Sajito** [comment]
I like to use the json, so I'd prefer the option there

**Comment by mageddo** [comment]
This feature will depends on #392 otherwise won't work as expected

**Comment by Sajito** [comment]
I think when we have this option, it is enabled and there is at least one other nameserver in the resolv.conf, then dps maybe should not use the remote solver, as it should be handled by the other nameservers. What do you think?

**Comment by mageddo** [comment]
I would add a specific option for that, introduce `--no-remote-servers`.

**Comment by Sajito** [comment]
Sounds good for me 👍

**Comment by mageddo** [comment]
Just released ` 3.15.10-snapshot` [see the docs][1] for the new option `resolvConfOverrideNameServers` . No remote servers option will be released in the sequence.

[1]: http://mageddo.github.io/dns-proxy-server/3.15/en/3-configuration/

**Comment by mageddo** [comment]
Finally released  `3.15.11-snapshot` [see the docs](http://mageddo.github.io/dns-proxy-server/3.15/en/3-configuration/) for the new option (No Remote Servers).

Can you check the released features? Then we can close this issue @Sajito.

**Comment by Sajito** [comment]
I've tested both features using this docker-compose config. I know the MG_RESOLVCONF is not needed, as it's detected automatically. But since my system uses systemd-resolved, it would be required to restart the systemd-resolved service. Using the /etc/resolv.conf directly does not require the system restart.
```
version: '3.6'

services:
  dns:
    image: defreitas/dns-proxy-server:3.15.11-snapshot
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc:/host/etc
    environment:
      MG_RESOLVCONF_OVERRIDE_NAMESERVERS: false
      MG_RESOLVCONF: /host/etc/resolv.conf
      MG_DPS_NETWORK: true
      MG_DPS_NETWORK_AUTO_CONNECT: true
      NO_REMOTE_SERVERS: true
      MG_LOG_LEVEL: DEBUG
    command: --no-remote-servers
    ports:
      - "5380:5380"
```

The `NO_REMOTE_SERVERS` environment variable does not seem to work. When adding only that variable, remote servers are still used. When using the cli option, it works fine.

The two features work as requested, but unfortunately the intended use-case still does not work. In fact, using both features together results in no external domains being resolved.
From my understanding that's the case, because DPS returns `NXDOMAIN`, when it has no result. `NXDOMAIN` from any nameserver causes the clients to stop trying any other nameserver (see https://superuser.com/a/1713739).

I'm not sure, but maybe returning `SERVFAIL` instead of `NXDOMAIN` might work? But that's really only an uneducated guess.
