### ISSUE TITLE
Documentation: hostname YAML property must be defined when using Docker Compose

### ISSUE THREAD

**Issue by wget** [mageddo/dns-proxy-server#418]
### What is expected

When deploying Dns Proxy Server to a bunch of Docker hosts, I realized that Docker Compose deployment for which no `hostname` was defined into the YAML file, that DPS cannot answer to the request even if the container name was the same.

Example:

```
name: wordpress-prod                    
services:                                   
  wordpress-prod-db:             
    image: mariadb:10.11       
                                       
    container_name: wordpress-prod-db
    hostname: wordpress-prod-db  
    environment:
      [...]
    volumes:                      
      - "/srv/my-server.com/data/db:/var/lib/mysql/"
    networks:                                                                                                                                                                                                                                                                                                               
      - wordpress-prod-network
    restart: always
    secrets:
      - [...]

networks:
  wordpress-prod-network:
    name: wordpress-prod-network

```


### What is Happening

We thought that DPS could handle the Docker Container names without having to specify `hostname` into the Docker Compose YAML file. After some tests, it appears this is needed.

### Changes (Optional)

Give an example with Docker Compose in the documentation and provide more explanation about the use of `hostname`.

**Comment by mageddo** [comment]
Hey @wget  , solve container using container `hostname` property or by it's container name are two individual features, they work separately. I agree a dedicated doc to explain they usage could help a lot. I tested all combinations on DPS 3.19.1-snapshot and all are looking great.




## Case 1 
```yaml
name: wordpress-prod
services:
  wordpress-prod-db:
    image: nginx
    container_name: wordpress-prod-db
    hostname: wordpress-prod-db-1
    networks:
      - wordpress-prod-network
    restart: always

networks:
  wordpress-prod-network:
    name: wordpress-prod-network
```

```bash
$  dig wordpress-prod-db.docker @127.0.0.1 -p 5354 +noall +answer

wordpress-prod-db.docker. 30	IN	A	172.29.0.2
```

## Case 2

```yaml
name: wordpress-prod
services:
  wordpress-prod-db:
    image: nginx
    container_name: wordpress-prod-db
#    hostname: wordpress-prod-db-1
    networks:
      - wordpress-prod-network
    restart: always

networks:
  wordpress-prod-network:
    name: wordpress-prod-network
```


```bash
$  dig wordpress-prod-db.docker @127.0.0.1 -p 5354 +noall +answer

wordpress-prod-db.docker. 30	IN	A	172.29.0.2
```

## Case 3 

```yaml
name: wordpress-prod
services:
  wordpress-prod-db:
    image: nginx
#    container_name: wordpress-prod-db
#    hostname: wordpress-prod-db-1
    networks:
      - wordpress-prod-network
    restart: always

networks:
  wordpress-prod-network:
    name: wordpress-prod-network
```

```shell
$ dig wordpress-prod-db.docker @127.0.0.1 -p 5354 +noall +answer
wordpress-prod-db.docker. 30	IN	A	172.29.0.2
```

## Case 4 

`hostname: wordpress-prod-db-1` will work but be aware of some [side effects][1], is better to set either the `domain` option or set a suffix domain at `hostname`e.g. `hostname: wordpress-prod-db-1.dev`. 

```yaml
name: wordpress-prod
services:
  wordpress-prod-db:
    image: nginx
#    container_name: wordpress-prod-db
    hostname: wordpress-prod-db-1
    networks:
      - wordpress-prod-network
    restart: always

networks:
  wordpress-prod-network:
    name: wordpress-prod-network
```

```shell
$ dig wordpress-prod-db-1 @127.0.0.1 -p 5354 +noall +answer
wordpress-prod-db-1. 30	IN	A	172.29.0.2
```


[1]: https://github.com/mageddo/dns-proxy-server/issues/54#issuecomment-350389315
