### ISSUE TITLE
LocalDB persist in docker and change ui port

### ISSUE THREAD

**Issue by karantin2020** [mageddo/dns-proxy-server#425]
### What is Happening / What is expected
* All dns config (set in ui) reset after docker restart
* Add persistent volume to save dns config

### Specs
* OS: Ubuntu 22.04 server
* Docker Version: latest
* DPS Version: 1.16.0

Read all docs, didn't find how to save dns config in docker or docker compose (latest version) before/after restart/stop container.
Is it possible to add environment variable to change web ui port?  

Thanks

**Comment by mageddo** [comment]
Hey, sorry for the late answer:

* You can create a persistent JSON config by voluming container path `/app/conf`
* You can change the webserver port on the JSON config or at the command args by using `--web-server-port 80` for example.


```yaml
services:
  dps:
    image: defreitas/dns-proxy-server:3.19.1-snapshot
    command: --web-server-port 80
    volumes:
      - dps_vol:/app/conf
    ports:
      - 8081:80

volumes: 
  dps_vol:
```

Please reopen if you have any doubts
