### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.github.dockerjava.transport.DomainSocket

### ISSUE THREAD

**Issue by mageddo** [mageddo/dns-proxy-server#465]
### What is Happening / What is expected

Docker socket is not volumed, then DPS container can't connect to docker and check it is running inside a container, the error `Could not initialize class com.github.dockerjava.transport.DomainSocket` is not suggestive for the root cause.

```
dps-1  | 11:29:55.831 [Thread-2       ] WAR c.m.d.dnsconfigurator.DnsConfigurators            l=59   m=lambda$configurationHook$0      status=failedToConfigureAsDefaultDns, path=/host/etc/systemd/resolved.conf,/host/etc/resolv.conf,/etc/systemd/resolved.conf,/etc/resolv.conf, msg=Could not initialize class com.github.dockerjava.transport.DomainSocket
dps-1  | java.lang.NoClassDefFoundError: Could not initialize class com.github.dockerjava.transport.DomainSocket
```
Logs attached
[logs.txt](https://github.com/user-attachments/files/15764938/logs.txt)

### Specs
```yaml
services:
  dps:
    image: defreitas/dns-proxy-server:3.19.1-snapshot
    command: --web-server-port 80
    volumes:
      - dps_vol:/app/conf

volumes: 
  dps_vol:
```

### Changes
* DnsConfigurators can't  fail just because DPS can't connect to docker API
* When failing to connect to docker API, thrown a more suggestive error, create a interceptor which always check docker connection before request docker via API
