### ISSUE TITLE
[issue] Support a mask in hostnames

### ISSUE THREAD

**Issue by spravo** [mageddo/dns-proxy-server#58]
Thank for your awesome project. Will your project support a mask in hostnames, like `test.com,*.test.com`.

Thank

**Comment by mageddo** [comment]
Thank you  for your feedback.

> Will your project support a mask in hostnames, like test.com,*.test.com

Did you mean for example, if I register a container with `*.test.com` hostname then  all it subdomains resolve to that container? A test case

```
docker run --hostname *.test.com nginx
```
Then when I try to solve 
```
nslookup mageddo.test.com
```
It points to NGINX container? If yes please describe a real world use case for that.

**Comment by spravo** [comment]
## Use case:

nginx.conf
```text
server {
    server_name ~^(?<subdomain>.*)\.test.dev;
    set $proxyhost backend;

    location = / {
        proxy_pass http://$proxyhost?subdomain=$subdomain;
    }
}
```

docker-compose.yml
```yml
dns-proxy-server:
   image: defreitas/dns-proxy-server
   name: dns-proxy-server
   hostname: dns.mageddo
   ports:
       - 5380:5380
  volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - /etc/resolv.conf:/etc/resolv.conf

nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
   environment:
       # Here I list all the hosts for the development mode
       - HOSTNAMES=test.dev,subdomain1.test.dev,subdomain2.test.dev
       # - HOSTNAMES=test.dev,*.test.dev
    volumes:
      - /host/path/nginx.conf:/etc/nginx/nginx.conf:ro
```
