### ISSUE TITLE
Bug: `current machine does not support all of the following`

### ISSUE THREAD

**Issue by SiriosDev** [mageddo/dns-proxy-server#586]
## What is Happening

Using the following compose (derived from the run recommended in the docs) the container does not start giving in the logs only the lack of some instruction sets (read the logs below)

the processor is an Intel(R) Celeron(R) J4125 CPU, so fairly recent, also I didn't put the suffix for arch

```yaml
version: "3.3"
services:
  dns-proxy-server:
    image: defreitas/dns-proxy-server
    hostname: dps
    container_name: dps
    restart: unless-stopped
    ports:
      - 5354:53/tcp
      - 5354:53/udp
      - 5380:5380
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment: []
    networks:
      - local
networks:
  local:
    external: true
```

## What is Expected

Describe what you expected to happen.

## Specs
* Docker Version: `27.3.1`
* DPS Version:  `latest` (cant run)
* Log
```log
dps  | The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
dps  | Please rebuild the executable with an appropriate setting of the -march option.The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
```
* OS: Debian 12

**Comment by julipercas** [comment]
I'm also having this problem only since recently, even though I've been using dps-dns in docker for months without issues.
* Docker version 24.0.2
* DPS version: latest
* OS: Ubuntu 18.04

**Comment by mageddo** [comment]
Looks like it's related to build optimizations,  [[1][1]] [[2][2]]

Can you confirm that version `3.26.0-snapshot` works great and `3.29.0-snapshot` don´t?

[1]: https://github.com/spring-projects/spring-boot/issues/36576
[2]: https://github.com/mageddo/dns-proxy-server/commit/eae70f13da6a40f397da0a3af824f22e9bb9cc74#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R222

**Comment by SiriosDev** [comment]
I've tried `3.24` `3.26` `latest` `nightly` and `3.30.2`, all same error

**Comment by mageddo** [comment]
Made an adjustment, releasing `3.30.4-snapshot` right now, try check it out later.

**Comment by SiriosDev** [comment]
Yep now work, in this moment u r the savior of my self host mental sanity

**Comment by SiriosDev** [comment]
For my needs it works perfectly, but I discovered that (I only think this one image because I can't try the old ones 😅) refuse to accept config in every form, trough env var some is ignored some cause error.At the same time the config file once bind causes a null point exception to be thrown

**Comment by mageddo** [comment]
@SiriosDev  can you elaborate an example for this issue you are getting? I made some tests and couldn´t reproduce

**Comment by SiriosDev** [comment]
Yep, this is my example, putting any kind of env var, the resulting container is always the same, with the pre set entry (`dps-sample.dev`), no domain etc etc
```yaml
services:
  dps:
    image: defreitas/dns-proxy-server:3.30.4-snapshot-amd64-static
    hostname: dps
    container_name: dps
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 5380:5380
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - local
    environment:
      - MG_DOMAIN="dkr"
      - MG_HOST_MACHINE_HOSTNAME="host.dkr"
      - MG_NO_REMOTE_SERVERS=true
networks:
  local:
    external: true
```
