### ISSUE TITLE
Compose not supported with latest docker

### ISSUE THREAD

**Issue by gliviu** [mageddo/dns-proxy-server#80]
According to [this answer](https://stackoverflow.com/a/45071126) and #70, DPS seem to have worked for containers started from docker compose.
Tried with docker version 18.03 and id din't work.

I used the compose file from SO answer.
```
version: '3'
services:
  redis:
    image: redis:2.8
    hostname: redis.dev.intranet
  elasticsearch:
    image: elasticsearch:2.2
    hostname: elasticsearch.dev.intranet
```
Started DPS with `docker run --rm --hostname dns.mageddo --na...`.

Then
```bash
> docker stack deploy -c compose.yaml dps_stack
Creating network dps_stack_default
Creating service dps_stack_elasticsearch
Creating service dps_stack_redis

> nslookup redis.dev.intranet
Server:         172.17.0.2
Address:        172.17.0.2#53

Non-authoritative answer:
Name:   redis.dev.intranet
Address: 10.0.0.4

> ping redis.dev.intranet
PING redis.dev.intranet (10.0.0.4) 56(84) bytes of data.
2 packets transmitted, 0 received, 100% packet loss, time 1007ms
```
Tried with `docker run` instead of compose and DPS correctly uses '172.17..' network.

**Specs:**
 - OS: `inux liviu 4.13.0-45-generic #50~16.04.1-Ubuntu SMP`
- Docker Version: `18.03.1-ce, build 9ee9f40`
- DPS Version: `2.5.4`
- Logs: [dps_stack.log](https://github.com/mageddo/dns-proxy-server/files/2173747/dps_stack.log)

**Comment by mageddo** [comment]
Thank you for your great question.

The main point here is that the containers (redis, elasticsearch) are running at different networks than dns-proxy-server so dns-proxy-server have not firewall permissions to talk with them, this is a docker premise

To make it work you'll  have to put then on same network, as I see you are using `docker stack deploy`, if you use `docker-compose up` you can put them on same network by adding `network_mode` option 

```yaml
version: '3'
services:
  server-01:
    image: alpine:3.7
    hostname: server-01.intranet
    command: sh -c 'apk add --update curl iputils bind-tools && tail -f /dev/null'
   network_mode: bridge
  server-02:
    image: alpine:3.7
    hostname: server-02.intranet
    command: sh -c 'apk add --update curl iputils bind-tools && tail -f /dev/null'
    network_mode: bridge
```

To make it work with `docker stack deploy` you'll have to use `networks` option (it works for docker-compose as well)

Creating a common network
```
docker network create --attachable --driver overlay github
```

```yaml
version: '3'
services:
  server-01:
    image: alpine:3.7
    hostname: server-01.intranet
    command: sh -c 'apk add --update curl iputils bind-tools && tail -f /dev/null'
    networks:
      - github
  server-02:
    image: alpine:3.7
    hostname: server-02.intranet
    command: sh -c 'apk add --update curl iputils bind-tools && tail -f /dev/null'
    networks:
      - github

networks:
  github:
    external: true
```

Then it should work, note that create a external network is necessary since all containers must ran at same network and DPS was started without docker stack deploy

If you don't want to manually create an external network then you will have to start DPS at the same stack file that way docker will create a network for that deploy and assign all those containers at same network

```yaml
version: '3'
services:
  dps:
    image: defreitas/dns-proxy-server
    hostname: dns.mageddo
    volumes:
      - /etc/resolv.conf:/etc/resolv.conf
      - /var/run/docker.sock:/var/run/docker.sock
  server-01:
    image: alpine:3.7
    hostname: server-01.intranet
    command: sh -c 'apk add --update curl iputils bind-tools && tail -f /dev/null'
    volumes:
      - /etc/resolv.conf:/etc/resolv.conf
  server-02:
    image: alpine:3.7
    hostname: server-02.intranet
    command: sh -c 'apk add --update curl iputils bind-tools && tail -f /dev/null'
    volumes:
      - /etc/resolv.conf:/etc/resolv.conf
```
The drawback is that you will have to volume resolv.conf to have sure others containers will bind it correctly 

**Observation**
Not related to your question but as you are using `docker stack deploy` you are using `docker swarm` you must be aware `DPS` will solve just containers started at the current machine, it will not solve containers from others cluster nodes.

**PS:** I used alpine container because is more lite to pull and start.
